docker:
  image: docker:latest
  services:
  - docker:dind

  script:
  - apk add make
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - make SUFFIX=ci-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA} GITLAB_AUTHN=gitlab-ci-token:${CI_JOB_TOKEN} install
