# you must also specify the node id and node cluster, e.g.,
# --config-yaml '{"node":{"cluster":"xds_cluster", "id":"egw-sample.sample-adhoc"}}'
admin:
  access_log_path: /dev/null
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901

# how to connect to the xDS control plane (i.e., marin3r-discoveryservice)
static_resources:
  clusters:
  - name: xds_cluster
    connect_timeout: 1s
    type: LOGICAL_DNS
    respect_dns_ttl: true
    load_assignment:
      cluster_name: xds_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: marin3r-discoveryservice
                port_value: 18000
    http2_protocol_options: {}
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        '@type': type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext
        common_tls_context:
          tls_certificate_sds_secret_configs:
            - sds_config:
                path: /etc/envoy/bootstrap/tls_certificate_sds_secret.json
    upstream_connection_options:
      # configure a TCP keep-alive to detect and reconnect to the admin
      # server in the event of a TCP socket half open connection
      tcp_keepalive:
        keepalive_probes: 3
        keepalive_time: 10
        keepalive_interval: 5

# Connect to the xDS control plane and download config from there
dynamic_resources:
  ads_config:
    transport_api_version: V2
    api_type: GRPC
    grpc_services:
      - envoy_grpc:
          cluster_name: xds_cluster
  cds_config:
    resource_api_version: V2
    ads: {}
  lds_config:
    resource_api_version: V2
    ads: {}

layered_runtime:
  layers:
    # the xds control plane is the baseline
    - name: rtds_layer
      rtds_layer:
        name: runtime
        rtds_config:
          resource_api_version: V2
          ads: {}
    # this allows overrides using the admin console
    - name: admin_layer
      admin_layer: {}
