apiVersion: epic.acnodal.io/v1
kind: ServiceGroup
metadata:
  generation: 1
  labels:
    owning-account: sample
    owning-serviceprefix: default
  name: sample
  namespace: epic-sample

spec:
  auth-creds: fredfredfredfred
  envoy-image: registry.gitlab.com/acnodal/epic/envoy:latest
  envoy-template:
    envoyResources:
      clusters:
      - name: template
        value: |
          name: {{.ClusterName}}
          connect_timeout: 2s
          lb_policy: MAGLEV
          load_assignment:
            cluster_name: {{.ClusterName}}
          {{- if .Endpoints}}
            endpoints:
            - lb_endpoints:
          {{- range .Endpoints}}
              - endpoint:
                  address:
                    socket_address:
                      address: {{.Spec.Address}}
                      protocol: {{.Spec.Port.Protocol | ToUpper}}
                      port_value: {{.Spec.Port.Port}}
          {{- end}}
          {{- end}}
      listeners:
      - name: template
        value: |
          name: {{.PortName}}
          address:
            socket_address:
              address: 0.0.0.0
              port_value: {{.Port}}
              protocol: {{.Protocol | ToUpper}}
          filter_chains:
            - filters:
              - name: envoy.filters.network.tcp_proxy
                config:
                    stats_prefix: ingress_tcp
                    cluster_name: {{.ClusterName}}
    nodeID: template
    serialization: yaml
